version: '3.9'

services:
  python:
    image: python:3.11-slim-buster
    build:
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - .:/workspace
    command: tail -f /dev/null
    environment:
      DATABASE_URL: postgresql://devuser:devpassword@<codespace_ip>:5432/devdb
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"

  node:
    image: node:16
    build:
      context: .
      dockerfile: node.Dockerfile
    volumes:
      - .:/workspace
    command: tail -f /dev/null
